# Generated by Django 3.1.5 on 2021-01-27 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIrest', '0002_auto_20210127_0018'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('event', 'participant')},
        ),
    ]
